### ISSUE TITLE
Add IMASDD to Julia registry

### ISSUE THREAD

**Issue by orso82** [ProjectTorreyPines/IMASdd.jl#11]
@JuliaRegistrator register()

**Comment by orso82** [comment]
@JuliaRegistrator register()

**Comment by orso82** [comment]
--------

Your new package pull request does not meet the guidelines for auto-merging. Please make sure that you have read the [General registry README](https://github.com/JuliaRegistries/General/blob/master/README.md) and the [AutoMerge guidelines](https://juliaregistries.github.io/RegistryCI.jl/stable/guidelines/). The following guidelines were not met:

Name does not meet all of the following: starts with an upper-case letter, ASCII alphanumerics only, not all letters are upper-case.
There is no compat entry for julia.
The following dependencies do not have a [compat] entry that is upper-bounded and only includes a finite number of breaking releases: AbstractTrees, DataInterpolations, HDF5, JSON, Memoize, OrderedCollections, PCHIPInterpolation, PrecompileTools, StaticArraysCore
Note that the guidelines are only required for the pull request to be merged automatically. However, it is strongly recommended to follow them, since otherwise the pull request needs to be manually reviewed and merged by a human.

After you have fixed the AutoMerge issues, simply retrigger Registrator, which will automatically update this pull request. You do not need to change the version number in your Project.toml file (unless of course the AutoMerge issue is that you skipped a version number, in which case you should change the version number).

If you do not want to fix the AutoMerge issues, please post a comment explaining why you would like this pull request to be manually merged. Then, send a message to the #pkg-registration channel in the [Julia Slack](https://julialang.org/slack/) to ask for help. Include a link to this pull request.

Since you are registering a new package, please make sure that you have also read the package naming guidelines: https://pkgdocs.julialang.org/v1/creating-packages/#Package-naming-guidelines

**Comment by anchal-physics** [comment]
Looking at this, I'll also add compat to the other repos whom we'll register soon. But this issue with their naming convention is really unfortunate, such an unnecessary requirement :(.
